### ISSUE TITLE
Summary of remaining changes required of the `cosmoDC2` model

### ISSUE THREAD

**Issue by aphearin** [LSSTDESC/cosmodc2#28]
This issue contains a list summarizing all planned model improvements prior to releasing `cosmoDC2` to the image simulation pipeline. For a comprehensive list that includes even very minor changes, see GitHub issues tagged with either the `next-release` or `cosmoDC2` milestone.

Anyone following this issue should feel free to use this as a space to place requests for modifications to the `cosmoDC2` model that are important to implement/calibrate/validate in the extragalactic catalog prior to sending the mock through the CatSim/PhoSim/ImSim image processing pipeline. 

### Remaining model modifications
 
- [x] recalibrate BOSS LOWZ number density (see #22 for details)
- [x] fix discrete jump in cluster central red sequence colors that occurs at Mhalo~3e13 (see #6 for details)
- [x] finish tuning faint-end of the luminosity function to recover power-law dn/dmag down to i<~28 (see #24 for details) 
- [x] implement gradual color evolution for z > 1 galaxies (see #23 for details)

CC @rmandelb @katrinheitmann @yymao @danielsf @dkorytov @evevkovacs @patricialarsen

### DESCQA results for the latest cosmoDC2 model 

For a full listing of the plots showing results that have been run through DESCQA with the latest cosmoDC2 model, see the following two pages:
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-07-19_4
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-07-19_5

These plots do not include redMaPPer-based results because those tests are not included in DESCQA. redMaPPer-specific validation test results will have their plots posted to their specific issues. 

### Accessing cosmoDC2 v0.1.0
**GCR**
Using the latest GCR version on NERSC, the catalog is labeled as ```cosmoDC2_v0.1.0``` or ```cosmoDC2_v0.1.0_test```. The ```test``` version loads faster by skipping a file checksum so it is better for exploratory/interactive use. Both catalog labels point to the same files.
**HDF5**
The raw hdf5 files can be found at nersc at ```/global/projecta/projectdirs/lsst/groups/CS/cosmoDC2/all_v0.1.0```
The files are broken up into redshift ranges and healpix pixels. There are about 30 files total.
